# Generated by Django 4.1.5 on 2023-01-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamparas',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='lamparas',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lamparas',
            name='tamaño',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mesas',
            name='color',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mesas',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mesas',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
