# Generated by Django 4.1.5 on 2023-02-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamparas',
            name='stock',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mesas',
            name='stock',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sillon',
            name='stock',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
