# Generated by Django 4.1.5 on 2023-02-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_lamparas_stock_mesas_stock_sillon_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamparas',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mesas',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sillon',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
