# Generated by Django 4.1.5 on 2023-02-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_alter_lamparas_stock_alter_mesas_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('comentario', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
